### ISSUE TITLE
Angabe 3: Leer + _ und (*)

### ISSUE THREAD

**Issue by Leralasss** [fsbier/fp-testsuite#2]
Vielen Dank für deine Tests - hab schon einige Fehler bei mir im Code gefunden!

Ein paar Ideen zu Testfällen:

**Leer + \_**
Sollte Leer+\_ nicht einen Error geben?
In der Testsuite steht es sollte Leer rauskommen, aber in der Definition steht ich nehme ein r aus der Menge vom Intervall, was aus der leeren Menge nicht geht oder?

**Multiplizieren (\*)**
In TestSuite3 ist ein Test **IV (2,5) * IV (-3,-2) = IV (-15,-4)**. Laut Definition ist aber IV(2,5)\*IV(-3,-2) = {2\*(-3),3\*(-3),4\*(-3),5\*(-3),2\*(-2),3\*(-2),4\*(-2),5\*(-2),} = {-6,-9,-12,-15,-4,-6,-8,-10}, aber kein Intervall IV(-4,15), da nicht alle Zahlen dazwischen enthalten sind.

![Github1](https://user-images.githubusercontent.com/10179385/97871556-fa404700-1d14-11eb-889c-e371c22be468.png)

**Comment by Nelathan** [comment]
Bei plus kommt fix dabei die leere menge raus

Bei Multiplikation sehe ich das problem aber was würdest du als ergebnis von (2,3)*(2,3) sehen. Per Definition ja [4,6,9]

**Comment by Nelathan** [comment]
Wurde jetzt genauer definiert und die Testcases angepasst
