### ISSUE TITLE
Revert Merge-Request #23

### ISSUE THREAD

**Issue by chrisiKern** [fsbier/fp-testsuite#26]
#23:

Es steht "Welche tatsächlich mit einem oder mehreren Kandidaten angetretene(n) Partei(en) hatte(n) als erste bei einer mit einem Wahlsieger oder in einer Wahlwiederholung endenden Wahl keine Kandidaten mehr im Rennen und waren damit die größten Wahlverlierer?". Da die Wahl mit einer Wahlwiederholung endet, soll auf jeden Fall ein Wahlverlierer zurückgegeben werden.

Am Schluss steht "Endet die Wahl NICHT mit einem Sieger ODER in einer Wiederholung, ist das Resultat Analyse_nicht_moeglich." Da ist das "nicht" auf beides bezogen denk ich.

Meiner Meinung ist diese Änderung somit falsch und sollte wieder zurückgesetzt werden.

**Comment by oolfloo** [comment]
Da hast du vollkommen recht. Sorry für's mergen.
