### ISSUE TITLE
errors in TestSuite5

### ISSUE THREAD

**Issue by sigmasternchen** [fsbier/fp-testsuite#28]
I think I found 2 mistakes in TestSuite5:

wan1: According to the example in the specification the result should be `GWV [MNO]`, not `GWV [ABC, MNO]` (page 5, version 201113).

wan12: A winner is selected before any party gets discarded. Therefore every party still has at least one candidate. Hence the result should be `Keine` instead.

**Comment by chrisiKern** [comment]
wan1: consider all valid stimmzettel from wahl1: `[[2,1,3],[1,2,3],[2,3,1]]`. 2 has the absolute majority, therefore 1 and 3 loose right away in the first round. Both of them are therefore the biggest losers.

wan12: No, all the other party's who didn't win are therefore losers.

**Comment by sigmasternchen** [comment]
Given that the test case directly contradicts the example in the specification I'm not so sure about that. 
My interpretation is: The function should return all parties that first lost all candidates in the race. To me it looks like "lost all candidates" is defined as loosing by elimination (= having the least amount of "1st place" votes) (cf. "Als aus dem Rennen genommen gelten dabei nach jeder Auszählung diejenigen Kandidaten mit den absolut wenigsten ‘Platz 1’-Stimmen.").

**Comment by sigmasternchen** [comment]
Regarding wan12: After thinking about it some more I came to the conclusion that the test case is right. But for a different reason: Giving the example in the specification the eliminination apparently has priority over the win condition. Meaning: In the turn candidate 5 wins 2 and 4 get discarded which in turn makes DEF and MNO the loosers.

**Comment by chrisiKern** [comment]
Ok, just saw that he changed that in the new Angabe. (I find it ridiculous how often this happens) You are right then about wan1. wan12 is a really weird case, cause it says "..., sonst ist das Analyseergebnis der Wert Keine (wenn nur Kandidaten einer Partei angetreten sind, von denen einer Wahlsieger wird)".

**Comment by Nelathan** [comment]
Is this still a problem or can i close it?

**Comment by chrisiKern** [comment]
I think you can close.
