### ISSUE TITLE
Wann kommt der Testsuite zur Angabe 4?

### ISSUE THREAD

**Issue by chrisiKern** [fsbier/fp-testsuite#9]

**Comment by Nelathan** [comment]
Ich bin noch nicht dazugekommen, du kannst gerne einen Pull request machen

**Comment by chrisiKern** [comment]
#10

**Comment by flofriday** [comment]
Ich hab ein paar testcases hinzugefügt für A4 und A5 mit #11.
Es fehlen aber noch immer Testcases für die Implementierung für Ord in A4 und generell könnten bei A4 Eq noch mehr ausgefallenere Testcases hinzugefügt werden.
